### PR TITLE
Use free instead of cfree.

### LINKED ISSUE #16: libycadgraywolf.so: undefined reference to `cfree'
Ubuntu 17.10, `cmake .`, `make`, then:

```
[ 52%] Building C object src/twmc/CMakeFiles/TimberWolfMC.dir/__/date/date.c.o
[ 53%] Linking C executable TimberWolfMC
/home/ciro/git/graywolf/src/Ylib/libycadgraywolf.so: undefined reference to `cfree'
collect2: error: ld returned 1 exit status
src/twmc/CMakeFiles/TimberWolfMC.dir/build.make:1785: recipe for target 'src/twmc/TimberWolfMC' failed
```

### PR DESCRIPTION
**Pull request by cirosantilli**
man cfree says:

This function should never be used.  Use free(3) instead.  Starting with version 2.26, it has been removed from glibc.

And thus this breaks the build in Ubuntu 17.10.

Fix #16

### CODE REVIEW

**Comment by cirosantilli** [comment]
OK, already at: https://github.com/rubund/graywolf/pull/15
